import {
  DiagramModelSchema,
  getTableColumns,
  serializeDiagramModel,
  type ColumnTypeSpec,
  type DatabaseCheck,
  type DatabaseColumn,
  type DatabaseDialect,
  type DatabaseIndex,
  type DatabaseRelationship,
  type DatabaseTable,
  type DiagramModel,
} from '@tabliodb/schema-core';

export type SqlDialect = DatabaseDialect;

export type GenerateSqlOptions = {
  dialect: SqlDialect;
  includeComments?: boolean;
};

export type SqlGenerationWarning = {
  code: string;
  message: string;
  target?: {
    id: string;
    type: 'check' | 'column' | 'enum' | 'index' | 'relationship' | 'table';
  };
};

type DialectDefinition = {
  autoIncrementKeyword?: string;
  identifierQuote: 'backtick' | 'bracket' | 'double';
  supportsCheckConstraints: boolean;
  supportsColumnComments: boolean;
  supportsDeferrableConstraints: boolean;
  supportsFilteredIndexes: boolean;
  supportsIndexInclude: boolean;
  supportsIndexMethods: boolean;
  supportsInlineEnum: boolean;
  supportsSchemas: boolean;
  supportsSeparateCommentStatements: boolean;
  supportsTableCommentOption: boolean;
  supportsUnsigned: boolean;
};

export const sqlDialectRegistry = {
  mariadb: {
    autoIncrementKeyword: 'AUTO_INCREMENT',
    identifierQuote: 'backtick',
    supportsCheckConstraints: true,
    supportsColumnComments: true,
    supportsDeferrableConstraints: false,
    supportsFilteredIndexes: false,
    supportsIndexInclude: false,
    supportsIndexMethods: true,
    supportsInlineEnum: true,
    supportsSchemas: true,
    supportsSeparateCommentStatements: false,
    supportsTableCommentOption: true,
    supportsUnsigned: true,
  },
  mysql: {
    autoIncrementKeyword: 'AUTO_INCREMENT',
    identifierQuote: 'backtick',
    supportsCheckConstraints: true,
    supportsColumnComments: true,
    supportsDeferrableConstraints: false,
    supportsFilteredIndexes: false,
    supportsIndexInclude: false,
    supportsIndexMethods: true,
    supportsInlineEnum: true,
    supportsSchemas: true,
    supportsSeparateCommentStatements: false,
    supportsTableCommentOption: true,
    supportsUnsigned: true,
  },
  postgresql: {
    autoIncrementKeyword: 'GENERATED BY DEFAULT AS IDENTITY',
    identifierQuote: 'double',
    supportsCheckConstraints: true,
    supportsColumnComments: false,
    supportsDeferrableConstraints: true,
    supportsFilteredIndexes: true,
    supportsIndexInclude: true,
    supportsIndexMethods: true,
    supportsInlineEnum: false,
    supportsSchemas: true,
    supportsSeparateCommentStatements: true,
    supportsTableCommentOption: false,
    supportsUnsigned: false,
  },
  sqlite: {
    identifierQuote: 'double',
    supportsCheckConstraints: true,
    supportsColumnComments: false,
    supportsDeferrableConstraints: false,
    supportsFilteredIndexes: true,
    supportsIndexInclude: false,
    supportsIndexMethods: false,
    supportsInlineEnum: false,
    supportsSchemas: false,
    supportsSeparateCommentStatements: false,
    supportsTableCommentOption: false,
    supportsUnsigned: false,
  },
  sqlserver: {
    autoIncrementKeyword: 'IDENTITY(1,1)',
    identifierQuote: 'bracket',
    supportsCheckConstraints: true,
    supportsColumnComments: false,
    supportsDeferrableConstraints: false,
    supportsFilteredIndexes: true,
    supportsIndexInclude: true,
    supportsIndexMethods: false,
    supportsInlineEnum: false,
    supportsSchemas: true,
    supportsSeparateCommentStatements: false,
    supportsTableCommentOption: false,
    supportsUnsigned: false,
  },
} as const satisfies Record<SqlDialect, DialectDefinition>;

export function generateCreateSchemaSql(model: DiagramModel, options: GenerateSqlOptions): string {
  return generateCreateSchemaSqlWithWarnings(model, options).sql;
}

export function generateCreateSchemaSqlWithWarnings(
  model: DiagramModel,
  options: GenerateSqlOptions,
): { sql: string; warnings: SqlGenerationWarning[] } {
  const normalizedModel = serializeDiagramModel(DiagramModelSchema.parse(model));
  const dialect = options.dialect;
  const includeComments = options.includeComments ?? true;
  const statements = [
    ...renderEnumStatements(normalizedModel, dialect),
    ...Object.values(normalizedModel.tables).map((table) =>
      renderCreateTableStatement(normalizedModel, table, options),
    ),
    ...renderIndexStatements(normalizedModel, dialect),
    ...(includeComments ? renderCommentStatements(normalizedModel, dialect) : []),
  ];

  return {
    // The generator returns a stable, reviewable SQL script with blank lines between logical schema sections.
    sql: `${statements.filter(Boolean).join('\n\n')}\n`,
    warnings: getSqlGenerationWarnings(normalizedModel, options),
  };
}

export function getSqlGenerationWarnings(model: DiagramModel, options: GenerateSqlOptions): SqlGenerationWarning[] {
  const normalizedModel = serializeDiagramModel(DiagramModelSchema.parse(model));
  const dialect = options.dialect;
  const definition: DialectDefinition = sqlDialectRegistry[dialect];
  const warnings: SqlGenerationWarning[] = [];
  const commentsEnabled = options.includeComments ?? true;

  for (const table of Object.values(normalizedModel.tables)) {
    if (table.schema && !definition.supportsSchemas) {
      warnings.push({
        code: 'schema_not_supported',
        message: `${dialect} export does not support schema-qualified table "${table.schema}.${table.name}".`,
        target: { id: table.id, type: 'table' },
      });
    }

    if (
      commentsEnabled &&
      table.comment &&
      !definition.supportsSeparateCommentStatements &&
      !definition.supportsTableCommentOption
    ) {
      warnings.push({
        code: 'table_comment_not_supported',
        message: `${dialect} export cannot emit table comment for "${table.name}".`,
        target: { id: table.id, type: 'table' },
      });
    }

    for (const column of getTableColumns(normalizedModel, table.id)) {
      if (column.unsigned && !definition.supportsUnsigned) {
        warnings.push({
          code: 'unsigned_not_supported',
          message: `${dialect} export ignores unsigned modifier on "${table.name}.${column.name}".`,
          target: { id: column.id, type: 'column' },
        });
      }

      if (column.generatedExpression) {
        warnings.push({
          code: 'generated_expression_not_supported',
          message: `Generated column expression on "${table.name}.${column.name}" is not emitted yet.`,
          target: { id: column.id, type: 'column' },
        });
      }

      if (
        commentsEnabled &&
        column.comment &&
        !definition.supportsColumnComments &&
        !definition.supportsSeparateCommentStatements
      ) {
        warnings.push({
          code: 'column_comment_not_supported',
          message: `${dialect} export cannot emit column comment for "${table.name}.${column.name}".`,
          target: { id: column.id, type: 'column' },
        });
      }

      if (column.type.family === 'enum' && !definition.supportsInlineEnum && dialect !== 'postgresql') {
        warnings.push({
          code: 'enum_fallback_to_text',
          message: `${dialect} export maps enum column "${table.name}.${column.name}" to text.`,
          target: { id: column.id, type: 'column' },
        });
      }
    }
  }

  for (const relationship of Object.values(normalizedModel.relationships)) {
    if (relationship.deferrable && !definition.supportsDeferrableConstraints) {
      warnings.push({
        code: 'deferrable_not_supported',
        message: `${dialect} export ignores deferrable setting on relationship "${relationship.name ?? relationship.id}".`,
        target: { id: relationship.id, type: 'relationship' },
      });
    }
  }

  for (const index of Object.values(normalizedModel.indexes)) {
    if (index.includeColumnIds?.length && !definition.supportsIndexInclude) {
      warnings.push({
        code: 'index_include_not_supported',
        message: `${dialect} export ignores INCLUDE columns on index "${index.name}".`,
        target: { id: index.id, type: 'index' },
      });
    }

    if (index.where && !definition.supportsFilteredIndexes) {
      warnings.push({
        code: 'filtered_index_not_supported',
        message: `${dialect} export ignores WHERE clause on index "${index.name}".`,
        target: { id: index.id, type: 'index' },
      });
    }

    if (index.method && !definition.supportsIndexMethods) {
      warnings.push({
        code: 'index_method_not_supported',
        message: `${dialect} export ignores method "${index.method}" on index "${index.name}".`,
        target: { id: index.id, type: 'index' },
      });
    }
  }

  return warnings;
}

function renderCreateTableStatement(model: DiagramModel, table: DatabaseTable, options: GenerateSqlOptions): string {
  const dialect = options.dialect;
  const includeComments = options.includeComments ?? true;
  const columns = getTableColumns(model, table.id);
  const primaryKeyColumns = columns.filter((column) => column.primaryKey);
  const checks = Object.values(model.checks).filter((check) => check.tableId === table.id);
  const relationships = Object.values(model.relationships).filter(
    (relationship) => relationship.targetTableId === table.id,
  );
  const bodyLines = [
    ...columns.map((column) =>
      renderColumn(column, model, dialect, {
        includeComments,
        renderInlinePrimaryKey: primaryKeyColumns.length === 1,
        renderInlineUnique: shouldRenderInlineUnique(model, column),
      }),
    ),
    primaryKeyColumns.length > 1 ? renderCompositePrimaryKey(primaryKeyColumns, table, dialect) : null,
    ...checks.flatMap((check) =>
      sqlDialectRegistry[dialect].supportsCheckConstraints ? [renderCheckConstraint(check, dialect)] : [],
    ),
    ...relationships.flatMap((relationship) => renderForeignKeyConstraint(model, relationship, dialect)),
  ].filter((line): line is string => Boolean(line));
  const body = bodyLines.length > 0 ? bodyLines.map((line) => `  ${line}`).join(',\n') : '  -- No columns defined yet';
  const tableComment =
    includeComments && sqlDialectRegistry[dialect].supportsTableCommentOption && table.comment
      ? ` COMMENT=${quoteStringLiteral(table.comment)}`
      : '';

  return `CREATE TABLE ${renderTableName(table, dialect)} (\n${body}\n)${tableComment};`;
}

function renderColumn(
  column: DatabaseColumn,
  model: DiagramModel,
  dialect: SqlDialect,
  options: {
    includeComments: boolean;
    renderInlinePrimaryKey: boolean;
    renderInlineUnique: boolean;
  },
): string {
  const definition: DialectDefinition = sqlDialectRegistry[dialect];
  const parts = [
    quoteIdentifier(column.name, dialect),
    renderType(column.type, model, dialect),
    column.unsigned && definition.supportsUnsigned ? 'UNSIGNED' : undefined,
    column.autoIncrement && definition.autoIncrementKeyword ? definition.autoIncrementKeyword : undefined,
    column.primaryKey && options.renderInlinePrimaryKey ? 'PRIMARY KEY' : undefined,
    column.nullable ? undefined : 'NOT NULL',
    column.unique && options.renderInlineUnique ? 'UNIQUE' : undefined,
    column.defaultValue ? `DEFAULT ${column.defaultValue}` : undefined,
    options.includeComments && column.comment && definition.supportsColumnComments
      ? `COMMENT ${quoteStringLiteral(column.comment)}`
      : undefined,
  ];

  // Undefined fragments are filtered so each dialect can opt into only the constraints it understands.
  return parts.filter(Boolean).join(' ');
}

function shouldRenderInlineUnique(model: DiagramModel, column: DatabaseColumn): boolean {
  const hasNamedSingleColumnUniqueIndex = Object.values(model.indexes).some(
    (index) =>
      index.tableId === column.tableId &&
      index.unique &&
      index.columns.length === 1 &&
      index.columns[0]?.columnId === column.id,
  );

  // If the user has a named unique index for this column, the index statement owns the SQL instead of duplicating UNIQUE inline.
  return !hasNamedSingleColumnUniqueIndex;
}

function renderCompositePrimaryKey(columns: DatabaseColumn[], table: DatabaseTable, dialect: SqlDialect): string {
  const constraintName = `${table.name}_pkey`;
  const columnNames = columns.map((column) => quoteIdentifier(column.name, dialect)).join(', ');

  return `CONSTRAINT ${quoteIdentifier(constraintName, dialect)} PRIMARY KEY (${columnNames})`;
}

function renderCheckConstraint(check: DatabaseCheck, dialect: SqlDialect): string {
  // Checks are table constraints so a later expression can reference multiple columns without changing the model shape.
  return `CONSTRAINT ${quoteIdentifier(check.name, dialect)} CHECK (${check.expression})`;
}

function renderForeignKeyConstraint(
  model: DiagramModel,
  relationship: DatabaseRelationship,
  dialect: SqlDialect,
): string[] {
  const sourceTable = model.tables[relationship.sourceTableId];
  const targetTable = model.tables[relationship.targetTableId];

  if (!sourceTable || !targetTable) {
    return [];
  }

  const sourceColumns = relationship.sourceColumnIds.flatMap((columnId) => {
    const column = model.columns[columnId];
    return column ? [quoteIdentifier(column.name, dialect)] : [];
  });
  const targetColumns = relationship.targetColumnIds.flatMap((columnId) => {
    const column = model.columns[columnId];
    return column ? [quoteIdentifier(column.name, dialect)] : [];
  });
  const targetColumnNames = relationship.targetColumnIds.flatMap((columnId) => {
    const column = model.columns[columnId];
    return column ? [column.name] : [];
  });

  if (sourceColumns.length === 0 || targetColumns.length === 0 || sourceColumns.length !== targetColumns.length) {
    return [];
  }

  const parts = [
    // The fallback constraint name uses raw column names first, then the final identifier quoting handles the active dialect.
    `CONSTRAINT ${quoteIdentifier(relationship.name ?? `${targetTable.name}_${targetColumnNames.join('_')}_fkey`, dialect)}`,
    `FOREIGN KEY (${targetColumns.join(', ')})`,
    `REFERENCES ${renderTableName(sourceTable, dialect)} (${sourceColumns.join(', ')})`,
    relationship.matchType && relationship.matchType !== 'simple' && dialect === 'postgresql'
      ? `MATCH ${relationship.matchType.toUpperCase()}`
      : undefined,
    relationship.onDelete ? `ON DELETE ${renderReferentialAction(relationship.onDelete)}` : undefined,
    relationship.onUpdate ? `ON UPDATE ${renderReferentialAction(relationship.onUpdate)}` : undefined,
    relationship.deferrable && sqlDialectRegistry[dialect].supportsDeferrableConstraints ? 'DEFERRABLE' : undefined,
  ];

  return [parts.filter(Boolean).join(' ')];
}

function renderIndexStatements(model: DiagramModel, dialect: SqlDialect): string[] {
  return Object.values(model.indexes).flatMap((index) => {
    const table = model.tables[index.tableId];

    if (!table || index.columns.length === 0) {
      return [];
    }

    const renderedColumns = index.columns.flatMap((indexColumn) => {
      const column = model.columns[indexColumn.columnId];

      if (!column) {
        return [];
      }

      const direction = indexColumn.order ? ` ${indexColumn.order.toUpperCase()}` : '';
      const nulls = indexColumn.nulls && dialect === 'postgresql' ? ` NULLS ${indexColumn.nulls.toUpperCase()}` : '';

      return [`${quoteIdentifier(column.name, dialect)}${direction}${nulls}`];
    });

    if (renderedColumns.length === 0) {
      return [];
    }

    const definition: DialectDefinition = sqlDialectRegistry[dialect];
    const unique = index.unique ? 'UNIQUE ' : '';
    const method = renderIndexMethod(index, dialect);
    const include =
      index.includeColumnIds?.length && definition.supportsIndexInclude
        ? ` INCLUDE (${renderIndexIncludeColumns(model, index, dialect).join(', ')})`
        : '';
    const where = index.where && definition.supportsFilteredIndexes ? ` WHERE ${index.where}` : '';

    return [
      `CREATE ${unique}INDEX ${quoteIdentifier(index.name, dialect)}${method} ON ${renderTableName(table, dialect)} (${renderedColumns.join(', ')})${include}${where};`,
    ];
  });
}

function renderIndexMethod(index: DatabaseIndex, dialect: SqlDialect): string {
  if (!index.method || !sqlDialectRegistry[dialect].supportsIndexMethods) {
    return '';
  }

  if (dialect === 'postgresql') {
    return ` USING ${index.method}`;
  }

  if ((dialect === 'mysql' || dialect === 'mariadb') && (index.method === 'btree' || index.method === 'hash')) {
    return ` USING ${index.method.toUpperCase()}`;
  }

  return '';
}

function renderIndexIncludeColumns(model: DiagramModel, index: DatabaseIndex, dialect: SqlDialect): string[] {
  return (index.includeColumnIds ?? []).flatMap((columnId) => {
    const column = model.columns[columnId];
    return column ? [quoteIdentifier(column.name, dialect)] : [];
  });
}

function renderType(type: ColumnTypeSpec, model: DiagramModel, dialect: SqlDialect): string {
  if (type.raw) {
    return type.raw;
  }

  if (type.family === 'enum') {
    return renderEnumType(type, model, dialect);
  }

  const typeRenderer = typeRenderers[dialect][type.family];

  return typeRenderer(type);
}

const typeRenderers = {
  mariadb: {
    bigint: () => 'BIGINT',
    boolean: () => 'BOOLEAN',
    date: () => 'DATE',
    decimal: (type) => `DECIMAL(${type.precision ?? 10}, ${type.scale ?? 2})`,
    float: () => 'DOUBLE',
    integer: () => 'INT',
    json: () => 'JSON',
    text: () => 'TEXT',
    time: () => 'TIME',
    timestamp: () => 'DATETIME',
    uuid: () => 'CHAR(36)',
    varchar: (type) => `VARCHAR(${type.length ?? 255})`,
  },
  mysql: {
    bigint: () => 'BIGINT',
    boolean: () => 'BOOLEAN',
    date: () => 'DATE',
    decimal: (type) => `DECIMAL(${type.precision ?? 10}, ${type.scale ?? 2})`,
    float: () => 'DOUBLE',
    integer: () => 'INT',
    json: () => 'JSON',
    text: () => 'TEXT',
    time: () => 'TIME',
    timestamp: () => 'DATETIME',
    uuid: () => 'CHAR(36)',
    varchar: (type) => `VARCHAR(${type.length ?? 255})`,
  },
  postgresql: {
    bigint: () => 'BIGINT',
    boolean: () => 'BOOLEAN',
    date: () => 'DATE',
    decimal: (type) => `NUMERIC(${type.precision ?? 10}, ${type.scale ?? 2})`,
    float: () => 'DOUBLE PRECISION',
    integer: () => 'INTEGER',
    json: () => 'JSONB',
    text: () => 'TEXT',
    time: () => 'TIME',
    timestamp: () => 'TIMESTAMPTZ',
    uuid: () => 'UUID',
    varchar: (type) => `VARCHAR(${type.length ?? 255})`,
  },
  sqlite: {
    bigint: () => 'INTEGER',
    boolean: () => 'INTEGER',
    date: () => 'TEXT',
    decimal: () => 'NUMERIC',
    float: () => 'REAL',
    integer: () => 'INTEGER',
    json: () => 'TEXT',
    text: () => 'TEXT',
    time: () => 'TEXT',
    timestamp: () => 'TEXT',
    uuid: () => 'TEXT',
    varchar: (type) => `VARCHAR(${type.length ?? 255})`,
  },
  sqlserver: {
    bigint: () => 'BIGINT',
    boolean: () => 'BIT',
    date: () => 'DATE',
    decimal: (type) => `DECIMAL(${type.precision ?? 10}, ${type.scale ?? 2})`,
    float: () => 'FLOAT',
    integer: () => 'INT',
    json: () => 'NVARCHAR(MAX)',
    text: () => 'NVARCHAR(MAX)',
    time: () => 'TIME',
    timestamp: () => 'DATETIME2',
    uuid: () => 'UNIQUEIDENTIFIER',
    varchar: (type) => `NVARCHAR(${type.length ?? 255})`,
  },
} satisfies Record<SqlDialect, Record<Exclude<ColumnTypeSpec['family'], 'enum'>, (type: ColumnTypeSpec) => string>>;

function renderEnumStatements(model: DiagramModel, dialect: SqlDialect): string[] {
  if (dialect !== 'postgresql') {
    return [];
  }

  return Object.values(model.enums).map((databaseEnum) => {
    const enumName = renderQualifiedName(databaseEnum.schema, databaseEnum.name, dialect);
    const values = databaseEnum.values.map(quoteStringLiteral).join(', ');

    // PostgreSQL enum types must be declared before tables can reference them.
    return `CREATE TYPE ${enumName} AS ENUM (${values});`;
  });
}

function renderEnumType(type: ColumnTypeSpec, model: DiagramModel, dialect: SqlDialect): string {
  const databaseEnum = type.enumId ? model.enums[type.enumId] : undefined;

  if (!databaseEnum) {
    return renderTextFallbackType(dialect);
  }

  if (dialect === 'postgresql') {
    return renderQualifiedName(databaseEnum.schema, databaseEnum.name, dialect);
  }

  if (sqlDialectRegistry[dialect].supportsInlineEnum) {
    return `ENUM(${databaseEnum.values.map(quoteStringLiteral).join(', ')})`;
  }

  return renderTextFallbackType(dialect);
}

function renderTextFallbackType(dialect: SqlDialect): string {
  return dialect === 'sqlserver' ? 'NVARCHAR(MAX)' : 'TEXT';
}

function renderCommentStatements(model: DiagramModel, dialect: SqlDialect): string[] {
  if (!sqlDialectRegistry[dialect].supportsSeparateCommentStatements) {
    return [];
  }

  return [
    ...Object.values(model.enums).flatMap((databaseEnum) =>
      databaseEnum.comment
        ? [
            `COMMENT ON TYPE ${renderQualifiedName(databaseEnum.schema, databaseEnum.name, dialect)} IS ${quoteStringLiteral(databaseEnum.comment)};`,
          ]
        : [],
    ),
    ...Object.values(model.tables).flatMap((table) => {
      const tableName = renderTableName(table, dialect);
      const columns = getTableColumns(model, table.id);
      const checks = Object.values(model.checks).filter((check) => check.tableId === table.id);
      const indexes = Object.values(model.indexes).filter((index) => index.tableId === table.id);

      return [
        table.comment ? `COMMENT ON TABLE ${tableName} IS ${quoteStringLiteral(table.comment)};` : null,
        ...columns.map((column) =>
          column.comment
            ? `COMMENT ON COLUMN ${tableName}.${quoteIdentifier(column.name, dialect)} IS ${quoteStringLiteral(column.comment)};`
            : null,
        ),
        ...checks.map((check) =>
          check.comment
            ? `COMMENT ON CONSTRAINT ${quoteIdentifier(check.name, dialect)} ON ${tableName} IS ${quoteStringLiteral(check.comment)};`
            : null,
        ),
        ...indexes.map((index) =>
          index.comment
            ? `COMMENT ON INDEX ${quoteIdentifier(index.name, dialect)} IS ${quoteStringLiteral(index.comment)};`
            : null,
        ),
      ].filter((statement): statement is string => Boolean(statement));
    }),
  ];
}

function renderTableName(table: DatabaseTable, dialect: SqlDialect): string {
  return renderQualifiedName(table.schema, table.name, dialect);
}

function renderQualifiedName(schema: string | undefined, name: string, dialect: SqlDialect): string {
  if (!schema || !sqlDialectRegistry[dialect].supportsSchemas) {
    return quoteIdentifier(name, dialect);
  }

  return `${quoteIdentifier(schema, dialect)}.${quoteIdentifier(name, dialect)}`;
}

function quoteIdentifier(value: string, dialect: SqlDialect): string {
  const quote = sqlDialectRegistry[dialect].identifierQuote;

  if (quote === 'backtick') {
    return `\`${value.replaceAll('`', '``')}\``;
  }

  if (quote === 'bracket') {
    return `[${value.replaceAll(']', ']]')}]`;
  }

  return `"${value.replaceAll('"', '""')}"`;
}

function quoteStringLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function renderReferentialAction(action: NonNullable<DatabaseRelationship['onDelete']>): string {
  return action.replaceAll('_', ' ').toUpperCase();
}
