import {
  DiagramModelSchema,
  createEmptyDiagramModel,
  getTableColumns,
  serializeDiagramModel,
  type ColumnTypeSpec,
  type DatabaseCheck,
  type DatabaseColumn,
  type DatabaseDialect,
  type DatabaseIndex,
  type DatabaseRelationship,
  type DatabaseTable,
  type DiagramModel,
} from '@tabliodb/schema-core';

export type SqlDialect = DatabaseDialect;

export type GenerateSqlOptions = {
  dialect: SqlDialect;
  includeComments?: boolean;
};

export type SqlGenerationWarning = {
  code: string;
  message: string;
  target?: {
    id: string;
    type: 'check' | 'column' | 'enum' | 'index' | 'relationship' | 'table';
  };
};

export type ParseSqlOptions = {
  dialect?: SqlDialect;
  diagramName?: string;
};

export type SqlImportWarning = {
  code:
    | 'empty_sql'
    | 'malformed_statement'
    | 'missing_referenced_table'
    | 'missing_table'
    | 'unsupported_column_type'
    | 'unsupported_constraint'
    | 'unsupported_statement';
  message: string;
  statement?: string;
};

type SqlImportContext = {
  enumIdsByName: Map<string, string>;
  model: DiagramModel;
  tableIdsByName: Map<string, string>;
  usedIds: Set<string>;
  warnings: SqlImportWarning[];
};

type ParsedColumnDefinition = {
  autoIncrement: boolean;
  defaultValue?: string;
  enumValues?: string[];
  nullable: boolean;
  primaryKey: boolean;
  type: ColumnTypeSpec;
  unique: boolean;
  unsigned: boolean;
};

type ParsedForeignKeyConstraint = {
  name?: string;
  onDelete?: DatabaseRelationship['onDelete'];
  onUpdate?: DatabaseRelationship['onUpdate'];
  referencedColumns: string[];
  referencedTable: SqlQualifiedName;
  targetColumns: string[];
};

type SqlQualifiedName = {
  name: string;
  schema?: string;
};

type DialectDefinition = {
  autoIncrementKeyword?: string;
  identifierQuote: 'backtick' | 'bracket' | 'double';
  supportsCheckConstraints: boolean;
  supportsColumnComments: boolean;
  supportsDeferrableConstraints: boolean;
  supportsFilteredIndexes: boolean;
  supportsIndexInclude: boolean;
  supportsIndexMethods: boolean;
  supportsInlineEnum: boolean;
  supportsSchemas: boolean;
  supportsSeparateCommentStatements: boolean;
  supportsTableCommentOption: boolean;
  supportsUnsigned: boolean;
};

export const sqlDialectRegistry = {
  mariadb: {
    autoIncrementKeyword: 'AUTO_INCREMENT',
    identifierQuote: 'backtick',
    supportsCheckConstraints: true,
    supportsColumnComments: true,
    supportsDeferrableConstraints: false,
    supportsFilteredIndexes: false,
    supportsIndexInclude: false,
    supportsIndexMethods: true,
    supportsInlineEnum: true,
    supportsSchemas: true,
    supportsSeparateCommentStatements: false,
    supportsTableCommentOption: true,
    supportsUnsigned: true,
  },
  mysql: {
    autoIncrementKeyword: 'AUTO_INCREMENT',
    identifierQuote: 'backtick',
    supportsCheckConstraints: true,
    supportsColumnComments: true,
    supportsDeferrableConstraints: false,
    supportsFilteredIndexes: false,
    supportsIndexInclude: false,
    supportsIndexMethods: true,
    supportsInlineEnum: true,
    supportsSchemas: true,
    supportsSeparateCommentStatements: false,
    supportsTableCommentOption: true,
    supportsUnsigned: true,
  },
  postgresql: {
    autoIncrementKeyword: 'GENERATED BY DEFAULT AS IDENTITY',
    identifierQuote: 'double',
    supportsCheckConstraints: true,
    supportsColumnComments: false,
    supportsDeferrableConstraints: true,
    supportsFilteredIndexes: true,
    supportsIndexInclude: true,
    supportsIndexMethods: true,
    supportsInlineEnum: false,
    supportsSchemas: true,
    supportsSeparateCommentStatements: true,
    supportsTableCommentOption: false,
    supportsUnsigned: false,
  },
  sqlite: {
    identifierQuote: 'double',
    supportsCheckConstraints: true,
    supportsColumnComments: false,
    supportsDeferrableConstraints: false,
    supportsFilteredIndexes: true,
    supportsIndexInclude: false,
    supportsIndexMethods: false,
    supportsInlineEnum: false,
    supportsSchemas: false,
    supportsSeparateCommentStatements: false,
    supportsTableCommentOption: false,
    supportsUnsigned: false,
  },
  sqlserver: {
    autoIncrementKeyword: 'IDENTITY(1,1)',
    identifierQuote: 'bracket',
    supportsCheckConstraints: true,
    supportsColumnComments: false,
    supportsDeferrableConstraints: false,
    supportsFilteredIndexes: true,
    supportsIndexInclude: true,
    supportsIndexMethods: false,
    supportsInlineEnum: false,
    supportsSchemas: true,
    supportsSeparateCommentStatements: false,
    supportsTableCommentOption: false,
    supportsUnsigned: false,
  },
} as const satisfies Record<SqlDialect, DialectDefinition>;

export function generateCreateSchemaSql(model: DiagramModel, options: GenerateSqlOptions): string {
  return generateCreateSchemaSqlWithWarnings(model, options).sql;
}

export function generateCreateSchemaSqlWithWarnings(
  model: DiagramModel,
  options: GenerateSqlOptions,
): { sql: string; warnings: SqlGenerationWarning[] } {
  const normalizedModel = serializeDiagramModel(DiagramModelSchema.parse(model));
  const dialect = options.dialect;
  const includeComments = options.includeComments ?? true;
  const statements = [
    ...renderEnumStatements(normalizedModel, dialect),
    ...Object.values(normalizedModel.tables).map((table) =>
      renderCreateTableStatement(normalizedModel, table, options),
    ),
    ...renderIndexStatements(normalizedModel, dialect),
    ...(includeComments ? renderCommentStatements(normalizedModel, dialect) : []),
  ];

  return {
    // The generator returns a stable, reviewable SQL script with blank lines between logical schema sections.
    sql: `${statements.filter(Boolean).join('\n\n')}\n`,
    warnings: getSqlGenerationWarnings(normalizedModel, options),
  };
}

export function getSqlGenerationWarnings(model: DiagramModel, options: GenerateSqlOptions): SqlGenerationWarning[] {
  const normalizedModel = serializeDiagramModel(DiagramModelSchema.parse(model));
  const dialect = options.dialect;
  const definition: DialectDefinition = sqlDialectRegistry[dialect];
  const warnings: SqlGenerationWarning[] = [];
  const commentsEnabled = options.includeComments ?? true;

  for (const table of Object.values(normalizedModel.tables)) {
    if (table.schema && !definition.supportsSchemas) {
      warnings.push({
        code: 'schema_not_supported',
        message: `${dialect} export does not support schema-qualified table "${table.schema}.${table.name}".`,
        target: { id: table.id, type: 'table' },
      });
    }

    if (
      commentsEnabled &&
      table.comment &&
      !definition.supportsSeparateCommentStatements &&
      !definition.supportsTableCommentOption
    ) {
      warnings.push({
        code: 'table_comment_not_supported',
        message: `${dialect} export cannot emit table comment for "${table.name}".`,
        target: { id: table.id, type: 'table' },
      });
    }

    for (const column of getTableColumns(normalizedModel, table.id)) {
      if (column.unsigned && !definition.supportsUnsigned) {
        warnings.push({
          code: 'unsigned_not_supported',
          message: `${dialect} export ignores unsigned modifier on "${table.name}.${column.name}".`,
          target: { id: column.id, type: 'column' },
        });
      }

      if (column.generatedExpression) {
        warnings.push({
          code: 'generated_expression_not_supported',
          message: `Generated column expression on "${table.name}.${column.name}" is not emitted yet.`,
          target: { id: column.id, type: 'column' },
        });
      }

      if (
        commentsEnabled &&
        column.comment &&
        !definition.supportsColumnComments &&
        !definition.supportsSeparateCommentStatements
      ) {
        warnings.push({
          code: 'column_comment_not_supported',
          message: `${dialect} export cannot emit column comment for "${table.name}.${column.name}".`,
          target: { id: column.id, type: 'column' },
        });
      }

      if (column.type.family === 'enum' && !definition.supportsInlineEnum && dialect !== 'postgresql') {
        warnings.push({
          code: 'enum_fallback_to_text',
          message: `${dialect} export maps enum column "${table.name}.${column.name}" to text.`,
          target: { id: column.id, type: 'column' },
        });
      }
    }
  }

  for (const relationship of Object.values(normalizedModel.relationships)) {
    if (relationship.deferrable && !definition.supportsDeferrableConstraints) {
      warnings.push({
        code: 'deferrable_not_supported',
        message: `${dialect} export ignores deferrable setting on relationship "${relationship.name ?? relationship.id}".`,
        target: { id: relationship.id, type: 'relationship' },
      });
    }
  }

  for (const index of Object.values(normalizedModel.indexes)) {
    if (index.includeColumnIds?.length && !definition.supportsIndexInclude) {
      warnings.push({
        code: 'index_include_not_supported',
        message: `${dialect} export ignores INCLUDE columns on index "${index.name}".`,
        target: { id: index.id, type: 'index' },
      });
    }

    if (index.where && !definition.supportsFilteredIndexes) {
      warnings.push({
        code: 'filtered_index_not_supported',
        message: `${dialect} export ignores WHERE clause on index "${index.name}".`,
        target: { id: index.id, type: 'index' },
      });
    }

    if (index.method && !definition.supportsIndexMethods) {
      warnings.push({
        code: 'index_method_not_supported',
        message: `${dialect} export ignores method "${index.method}" on index "${index.name}".`,
        target: { id: index.id, type: 'index' },
      });
    }
  }

  return warnings;
}

export function parseCreateSchemaSql(
  sql: string,
  options: ParseSqlOptions = {},
): { model: DiagramModel; warnings: SqlImportWarning[] } {
  const dialect = options.dialect ?? 'postgresql';
  const context: SqlImportContext = {
    enumIdsByName: new Map(),
    model: createEmptyDiagramModel(options.diagramName ?? 'Imported SQL', dialect),
    tableIdsByName: new Map(),
    usedIds: new Set(),
    warnings: [],
  };
  const statements = splitSqlStatements(stripSqlComments(sql));
  const handledStatementIndexes = new Set<number>();

  if (statements.length === 0) {
    context.warnings.push({
      code: 'empty_sql',
      message: 'SQL import did not find any statements.',
    });
  }

  statements.forEach((statement, index) => {
    if (parseCreateEnumStatement(context, statement)) {
      handledStatementIndexes.add(index);
    }
  });

  statements.forEach((statement, index) => {
    if (!handledStatementIndexes.has(index) && parseCreateTableStatement(context, statement)) {
      handledStatementIndexes.add(index);
    }
  });

  statements.forEach((statement, index) => {
    if (handledStatementIndexes.has(index)) {
      return;
    }

    if (parseCreateIndexStatement(context, statement) || parseAlterTableForeignKeyStatement(context, statement)) {
      handledStatementIndexes.add(index);
      return;
    }

    context.warnings.push({
      code: 'unsupported_statement',
      message: 'SQL import skipped an unsupported statement.',
      statement,
    });
  });

  return {
    model: serializeDiagramModel(context.model),
    warnings: context.warnings,
  };
}

function parseCreateEnumStatement(context: SqlImportContext, statement: string): boolean {
  const match = statement.match(/^CREATE\s+TYPE\s+([\s\S]+?)\s+AS\s+ENUM\s*\(([\s\S]*)\)$/i);

  if (!match) {
    return false;
  }

  const enumName = parseQualifiedName(match[1] ?? '');
  const values = parseSqlStringList(match[2] ?? '');
  const enumId = createUniqueId(context, 'enum', qualifiedNameKey(enumName));

  context.model.enums[enumId] = {
    id: enumId,
    name: enumName.name,
    schema: enumName.schema,
    values,
  };
  rememberEnum(context, enumName, enumId);

  return true;
}

function parseCreateTableStatement(context: SqlImportContext, statement: string): boolean {
  const prefixMatch = statement.match(/^CREATE\s+(?:TEMPORARY\s+|TEMP\s+)?TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?/i);

  if (!prefixMatch) {
    return false;
  }

  const rest = statement.slice(prefixMatch[0].length).trim();
  const bodyStart = findTopLevelCharacter(rest, '(');

  if (bodyStart < 0) {
    context.warnings.push({
      code: 'malformed_statement',
      message: 'CREATE TABLE statement does not contain a column list.',
      statement,
    });
    return true;
  }

  const bodyEnd = findMatchingParenthesis(rest, bodyStart);

  if (bodyEnd < 0) {
    context.warnings.push({
      code: 'malformed_statement',
      message: 'CREATE TABLE statement has an unterminated column list.',
      statement,
    });
    return true;
  }

  const tableName = parseQualifiedName(rest.slice(0, bodyStart).replace(/^ONLY\s+/i, ''));
  const tableId = createUniqueId(context, 'table', qualifiedNameKey(tableName));
  const tableIndex = Object.keys(context.model.tables).length;
  const constraintFragments: string[] = [];

  context.model.tables[tableId] = {
    columnIds: [],
    id: tableId,
    indexIds: [],
    name: tableName.name,
    position: {
      x: 80 + (tableIndex % 3) * 380,
      y: 96 + Math.floor(tableIndex / 3) * 280,
    },
    schema: tableName.schema,
    width: 288,
  };
  rememberTable(context, tableName, tableId);

  for (const fragment of splitTopLevel(rest.slice(bodyStart + 1, bodyEnd), ',')) {
    if (isTableConstraintFragment(fragment)) {
      constraintFragments.push(fragment);
      continue;
    }

    parseColumnDefinition(context, tableId, fragment);
  }

  constraintFragments.forEach((fragment) => applyTableConstraint(context, tableId, fragment));

  return true;
}

function parseColumnDefinition(context: SqlImportContext, tableId: string, fragment: string) {
  const table = context.model.tables[tableId];
  const identifier = readLeadingIdentifier(fragment);

  if (!table || !identifier) {
    context.warnings.push({
      code: 'malformed_statement',
      message: `SQL import could not read column definition "${fragment}".`,
      statement: fragment,
    });
    return;
  }

  const { constraints, typeRaw } = splitColumnTypeAndConstraints(identifier.rest);
  const parsedColumn = parseColumnShape(context, table, identifier.value, typeRaw, constraints);
  const columnId = createUniqueId(context, 'column', `${table.id}-${identifier.value}`);

  context.model.columns[columnId] = {
    autoIncrement: parsedColumn.autoIncrement,
    defaultValue: parsedColumn.defaultValue,
    id: columnId,
    name: identifier.value,
    nullable: parsedColumn.nullable,
    primaryKey: parsedColumn.primaryKey,
    tableId,
    type: parsedColumn.type,
    unique: parsedColumn.unique,
    unsigned: parsedColumn.unsigned,
  };
  table.columnIds.push(columnId);

  if (parsedColumn.enumValues) {
    const enumName = { name: `${table.name}_${identifier.value}_enum`, schema: table.schema };
    const enumId = createUniqueId(context, 'enum', qualifiedNameKey(enumName));

    context.model.enums[enumId] = {
      id: enumId,
      name: enumName.name,
      schema: enumName.schema,
      values: parsedColumn.enumValues,
    };
    rememberEnum(context, enumName, enumId);
    context.model.columns[columnId] = {
      ...context.model.columns[columnId],
      type: { enumId, family: 'enum' },
    };
  }

  const inlineForeignKey = parseInlineForeignKeyConstraint(constraints, identifier.value);

  if (inlineForeignKey) {
    createRelationshipFromConstraint(context, tableId, inlineForeignKey);
  }
}

function parseColumnShape(
  context: SqlImportContext,
  table: DatabaseTable,
  columnName: string,
  typeRaw: string,
  constraints: string,
): ParsedColumnDefinition {
  const type = parseColumnType(context, table, columnName, typeRaw);
  const primaryKey = /\bPRIMARY\s+KEY\b/i.test(constraints);
  const notNull = /\bNOT\s+NULL\b/i.test(constraints);
  const nullable = !(primaryKey || notNull);
  const autoIncrement =
    /\b(?:BIGSERIAL|SERIAL|SMALLSERIAL)\b/i.test(typeRaw) ||
    /\b(?:AUTO_INCREMENT|IDENTITY)\b/i.test(constraints) ||
    /\bGENERATED\s+(?:ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY\b/i.test(constraints);
  const enumValues = parseInlineEnumValues(typeRaw);

  return {
    autoIncrement,
    defaultValue: extractDefaultValue(constraints),
    enumValues,
    nullable,
    primaryKey,
    type,
    unique: /\bUNIQUE\b/i.test(constraints),
    unsigned: /\bUNSIGNED\b/i.test(typeRaw) || /\bUNSIGNED\b/i.test(constraints),
  };
}

function parseColumnType(
  context: SqlImportContext,
  table: DatabaseTable,
  columnName: string,
  typeRaw: string,
): ColumnTypeSpec {
  const inlineEnumValues = parseInlineEnumValues(typeRaw);

  if (inlineEnumValues) {
    return { family: 'enum' };
  }

  const normalizedType = typeRaw
    .trim()
    .replace(/\bUNSIGNED\b/gi, '')
    .replace(/\s+/g, ' ');
  const lowerType = normalizedType.toLowerCase();
  const enumId = context.enumIdsByName.get(lowerType) ?? context.enumIdsByName.get(stripIdentifierQuotes(lowerType));

  if (enumId) {
    return { enumId, family: 'enum' };
  }

  if (/^(uuid|uniqueidentifier)$/i.test(normalizedType) || /^char\s*\(\s*36\s*\)$/i.test(normalizedType)) {
    return { family: 'uuid' };
  }

  const varcharLength = normalizedType.match(/^(?:var)?char(?:acter varying)?|^nvarchar/i)
    ? normalizedType.match(/\(\s*(\d+)\s*\)/)?.[1]
    : undefined;

  if (/^(?:var)?char|^character varying|^nvarchar/i.test(normalizedType)) {
    return { family: 'varchar', length: varcharLength ? Number(varcharLength) : undefined };
  }

  if (/^(text|clob|longtext|mediumtext|tinytext)\b/i.test(normalizedType)) {
    return { family: 'text' };
  }

  if (/^(bigint|bigserial)\b/i.test(normalizedType)) {
    return { family: 'bigint' };
  }

  if (/^(int|integer|serial|smallint|smallserial|tinyint)\b/i.test(normalizedType)) {
    return /^tinyint\s*\(\s*1\s*\)/i.test(normalizedType) ? { family: 'boolean' } : { family: 'integer' };
  }

  if (/^(bool|boolean|bit)\b/i.test(normalizedType)) {
    return { family: 'boolean' };
  }

  if (/^(decimal|numeric|number)\b/i.test(normalizedType)) {
    const precisionMatch = normalizedType.match(/\(\s*(\d+)(?:\s*,\s*(\d+))?\s*\)/);

    return {
      family: 'decimal',
      precision: precisionMatch?.[1] ? Number(precisionMatch[1]) : undefined,
      scale: precisionMatch?.[2] ? Number(precisionMatch[2]) : undefined,
    };
  }

  if (/^(float|double|real)\b/i.test(normalizedType)) {
    return { family: 'float' };
  }

  if (/^(json|jsonb)\b/i.test(normalizedType)) {
    return { family: 'json' };
  }

  if (/^date\b/i.test(normalizedType)) {
    return { family: 'date' };
  }

  if (/^time\b/i.test(normalizedType)) {
    return { family: 'time' };
  }

  if (/^(timestamp|timestamptz|datetime)\b/i.test(normalizedType)) {
    return { family: 'timestamp' };
  }

  context.warnings.push({
    code: 'unsupported_column_type',
    message: `SQL import kept "${table.name}.${columnName}" type "${normalizedType}" as a raw type.`,
    statement: typeRaw,
  });

  return { family: 'text', raw: normalizedType || typeRaw.trim() || 'TEXT' };
}

function applyTableConstraint(context: SqlImportContext, tableId: string, fragment: string) {
  const { body, name } = stripConstraintName(fragment);

  if (/^PRIMARY\s+KEY\b/i.test(body)) {
    const columnNames = parseFirstColumnList(body);

    columnNames.forEach((columnName) => {
      const columnId = findColumnIdByName(context, tableId, columnName);

      if (columnId) {
        context.model.columns[columnId] = {
          ...context.model.columns[columnId],
          nullable: false,
          primaryKey: true,
        };
      }
    });
    return;
  }

  if (/^UNIQUE\b/i.test(body)) {
    const columnNames = parseFirstColumnList(body);
    const columnIds = columnNames.flatMap((columnName) => {
      const columnId = findColumnIdByName(context, tableId, columnName);
      return columnId ? [columnId] : [];
    });

    if (columnIds.length === 1) {
      const columnId = columnIds[0]!;
      context.model.columns[columnId] = { ...context.model.columns[columnId], unique: true };
    }

    if (columnIds.length > 0) {
      createIndex(context, tableId, {
        columns: columnIds,
        name: name ?? `${context.model.tables[tableId]?.name ?? 'table'}_${columnNames.join('_')}_key`,
        unique: true,
      });
    }
    return;
  }

  if (/^(?:KEY|INDEX)\b/i.test(body)) {
    const table = context.model.tables[tableId];
    const indexNameMatch = body.match(/^(?:KEY|INDEX)\s+([^\s(]+)/i);
    const columnNames = parseFirstColumnList(body);
    const columnIds = columnNames.flatMap((columnName) => {
      const columnId = findColumnIdByName(context, tableId, columnName);
      return columnId ? [columnId] : [];
    });

    if (table && columnIds.length > 0) {
      createIndex(context, tableId, {
        columns: columnIds,
        name: indexNameMatch?.[1]
          ? normalizeIdentifier(indexNameMatch[1])
          : `${table.name}_${columnNames.join('_')}_idx`,
        unique: false,
      });
    }
    return;
  }

  if (/^FOREIGN\s+KEY\b/i.test(body)) {
    const foreignKey = parseForeignKeyConstraint(body, name);

    if (foreignKey) {
      createRelationshipFromConstraint(context, tableId, foreignKey);
      return;
    }
  }

  if (/^CHECK\b/i.test(body)) {
    const checkExpression = readParenthesizedContent(body, body.search(/\(/));
    const table = context.model.tables[tableId];

    if (table && checkExpression) {
      const checkId = createUniqueId(context, 'check', `${table.name}-${name ?? 'check'}`);
      context.model.checks[checkId] = {
        expression: checkExpression,
        id: checkId,
        name: name ?? `${table.name}_check_${Object.keys(context.model.checks).length + 1}`,
        tableId,
      };
      return;
    }
  }

  context.warnings.push({
    code: 'unsupported_constraint',
    message: `SQL import skipped unsupported table constraint "${fragment}".`,
    statement: fragment,
  });
}

function parseCreateIndexStatement(context: SqlImportContext, statement: string): boolean {
  const mysqlMatch = statement.match(
    /^CREATE\s+(UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?([\s\S]+?)\s+USING\s+(\w+)\s+ON\s+([\s\S]+)$/i,
  );
  const standardMatch =
    mysqlMatch ??
    statement.match(/^CREATE\s+(UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?([\s\S]+?)\s+ON\s+([\s\S]+)$/i);

  if (!standardMatch) {
    return false;
  }

  const unique = Boolean(standardMatch[1]);
  const indexName = normalizeIdentifier(standardMatch[2] ?? '');
  const methodFromPrefix = mysqlMatch?.[3]?.toLowerCase() as DatabaseIndex['method'] | undefined;
  const afterOn = (mysqlMatch ? mysqlMatch[4] : standardMatch[3]) ?? '';
  const columnsStart = findTopLevelCharacter(afterOn, '(');

  if (columnsStart < 0) {
    context.warnings.push({
      code: 'malformed_statement',
      message: 'CREATE INDEX statement does not contain a column list.',
      statement,
    });
    return true;
  }

  const columnsEnd = findMatchingParenthesis(afterOn, columnsStart);
  const tablePart = afterOn
    .slice(0, columnsStart)
    .trim()
    .replace(/^ONLY\s+/i, '');
  const tableMethodMatch = tablePart.match(/^([\s\S]+?)\s+USING\s+(\w+)$/i);
  const tableName = parseQualifiedName(tableMethodMatch?.[1] ?? tablePart);
  const tableId = resolveTableId(context, tableName);

  if (!tableId) {
    context.warnings.push({
      code: 'missing_table',
      message: `CREATE INDEX references missing table "${formatQualifiedName(tableName)}".`,
      statement,
    });
    return true;
  }

  const columns = parseColumnList(afterOn.slice(columnsStart + 1, columnsEnd)).flatMap((columnName) => {
    const columnId = findColumnIdByName(context, tableId, columnName);
    return columnId ? [columnId] : [];
  });

  createIndex(context, tableId, {
    columns,
    method: methodFromPrefix ?? (tableMethodMatch?.[2]?.toLowerCase() as DatabaseIndex['method'] | undefined),
    name: indexName,
    unique,
    where: afterOn
      .slice(columnsEnd + 1)
      .match(/\bWHERE\s+([\s\S]+)$/i)?.[1]
      ?.trim(),
  });

  return true;
}

function parseAlterTableForeignKeyStatement(context: SqlImportContext, statement: string): boolean {
  const match = statement.match(/^ALTER\s+TABLE\s+([\s\S]+?)\s+ADD\s+([\s\S]+)$/i);

  if (!match) {
    return false;
  }

  const tableName = parseQualifiedName((match[1] ?? '').replace(/^ONLY\s+/i, ''));
  const tableId = resolveTableId(context, tableName);

  if (!tableId) {
    context.warnings.push({
      code: 'missing_table',
      message: `ALTER TABLE references missing table "${formatQualifiedName(tableName)}".`,
      statement,
    });
    return true;
  }

  const { body, name } = stripConstraintName(match[2] ?? '');
  const foreignKey = parseForeignKeyConstraint(body, name);

  if (!foreignKey) {
    context.warnings.push({
      code: 'unsupported_constraint',
      message: 'ALTER TABLE statement is supported only for ADD FOREIGN KEY constraints in SQL import.',
      statement,
    });
    return true;
  }

  createRelationshipFromConstraint(context, tableId, foreignKey);

  return true;
}

function parseForeignKeyConstraint(body: string, name?: string): ParsedForeignKeyConstraint | null {
  const match = body.match(/^FOREIGN\s+KEY\s*\(([\s\S]+?)\)\s+REFERENCES\s+([\s\S]+?)\s*\(([\s\S]+?)\)([\s\S]*)$/i);

  if (!match) {
    return null;
  }

  return {
    name,
    onDelete: parseReferentialAction(match[4] ?? '', 'DELETE'),
    onUpdate: parseReferentialAction(match[4] ?? '', 'UPDATE'),
    referencedColumns: parseColumnList(match[3] ?? ''),
    referencedTable: parseQualifiedName(match[2] ?? ''),
    targetColumns: parseColumnList(match[1] ?? ''),
  };
}

function parseInlineForeignKeyConstraint(body: string, columnName: string): ParsedForeignKeyConstraint | null {
  const match = body.match(/\bREFERENCES\s+([\s\S]+?)\s*\(([\s\S]+?)\)([\s\S]*)$/i);

  if (!match) {
    return null;
  }

  return {
    onDelete: parseReferentialAction(match[3] ?? '', 'DELETE'),
    onUpdate: parseReferentialAction(match[3] ?? '', 'UPDATE'),
    referencedColumns: parseColumnList(match[2] ?? ''),
    referencedTable: parseQualifiedName(match[1] ?? ''),
    targetColumns: [columnName],
  };
}

function createRelationshipFromConstraint(
  context: SqlImportContext,
  targetTableId: string,
  constraint: ParsedForeignKeyConstraint,
) {
  const sourceTableId = resolveTableId(context, constraint.referencedTable);
  const targetTable = context.model.tables[targetTableId];

  if (!sourceTableId || !targetTable) {
    context.warnings.push({
      code: 'missing_referenced_table',
      message: `Foreign key references missing table "${formatQualifiedName(constraint.referencedTable)}".`,
    });
    return;
  }

  const sourceColumnIds = constraint.referencedColumns.flatMap((columnName) => {
    const columnId = findColumnIdByName(context, sourceTableId, columnName);
    return columnId ? [columnId] : [];
  });
  const targetColumnIds = constraint.targetColumns.flatMap((columnName) => {
    const columnId = findColumnIdByName(context, targetTableId, columnName);
    return columnId ? [columnId] : [];
  });

  if (
    sourceColumnIds.length === 0 ||
    targetColumnIds.length === 0 ||
    sourceColumnIds.length !== targetColumnIds.length
  ) {
    context.warnings.push({
      code: 'missing_referenced_table',
      message: `Foreign key "${constraint.name ?? targetTable.name}" has unresolved columns.`,
    });
    return;
  }

  const relationshipId = createUniqueId(context, 'relationship', constraint.name ?? `${targetTable.name}-fkey`);

  context.model.relationships[relationshipId] = {
    cardinality: 'one_to_many',
    id: relationshipId,
    name: constraint.name,
    onDelete: constraint.onDelete,
    onUpdate: constraint.onUpdate,
    sourceColumnIds,
    sourceTableId,
    targetColumnIds,
    targetTableId,
  };
}

function createIndex(
  context: SqlImportContext,
  tableId: string,
  input: {
    columns: string[];
    method?: DatabaseIndex['method'];
    name: string;
    unique: boolean;
    where?: string;
  },
) {
  const table = context.model.tables[tableId];

  if (!table || input.columns.length === 0) {
    return;
  }

  const indexId = createUniqueId(context, 'index', input.name);

  context.model.indexes[indexId] = {
    columns: input.columns.map((columnId) => ({ columnId })),
    id: indexId,
    method: input.method,
    name: input.name,
    tableId,
    unique: input.unique,
    where: input.where,
  };
  table.indexIds.push(indexId);
}

function splitSqlStatements(sql: string): string[] {
  const statements: string[] = [];
  let current = '';
  let depth = 0;
  let quote: "'" | '"' | '`' | '[' | null = null;

  for (let index = 0; index < sql.length; index += 1) {
    const char = sql[index]!;
    const next = sql[index + 1];

    current += char;

    if (quote) {
      if (quote === "'" && char === "'" && next === "'") {
        current += next;
        index += 1;
        continue;
      }

      if (quote === '"' && char === '"' && next === '"') {
        current += next;
        index += 1;
        continue;
      }

      if (quote === '`' && char === '`' && next === '`') {
        current += next;
        index += 1;
        continue;
      }

      if (quote === '[' && char === ']' && next === ']') {
        current += next;
        index += 1;
        continue;
      }

      if ((quote === '[' && char === ']') || (quote !== '[' && char === quote)) {
        quote = null;
      }
      continue;
    }

    if (char === "'" || char === '"' || char === '`' || char === '[') {
      quote = char;
      continue;
    }

    if (char === '(') {
      depth += 1;
      continue;
    }

    if (char === ')') {
      depth = Math.max(0, depth - 1);
      continue;
    }

    if (char === ';' && depth === 0) {
      const statement = current.slice(0, -1).trim();

      if (statement) {
        statements.push(statement);
      }
      current = '';
    }
  }

  const tail = current.trim();

  if (tail) {
    statements.push(tail);
  }

  return statements;
}

function stripSqlComments(sql: string): string {
  let result = '';
  let quote: "'" | '"' | '`' | '[' | null = null;

  for (let index = 0; index < sql.length; index += 1) {
    const char = sql[index]!;
    const next = sql[index + 1];

    if (quote) {
      result += char;

      if (quote === "'" && char === "'" && next === "'") {
        result += next;
        index += 1;
        continue;
      }

      if (quote === '"' && char === '"' && next === '"') {
        result += next;
        index += 1;
        continue;
      }

      if (quote === '`' && char === '`' && next === '`') {
        result += next;
        index += 1;
        continue;
      }

      if (quote === '[' && char === ']' && next === ']') {
        result += next;
        index += 1;
        continue;
      }

      if ((quote === '[' && char === ']') || (quote !== '[' && char === quote)) {
        quote = null;
      }
      continue;
    }

    if (char === "'" || char === '"' || char === '`' || char === '[') {
      quote = char;
      result += char;
      continue;
    }

    if (char === '-' && next === '-') {
      while (index < sql.length && sql[index] !== '\n') {
        index += 1;
      }
      result += '\n';
      continue;
    }

    if (char === '/' && next === '*') {
      index += 2;
      while (index < sql.length && !(sql[index] === '*' && sql[index + 1] === '/')) {
        index += 1;
      }
      index += 1;
      result += ' ';
      continue;
    }

    result += char;
  }

  return result;
}

function splitTopLevel(input: string, separator: string): string[] {
  const fragments: string[] = [];
  let current = '';
  let depth = 0;
  let quote: "'" | '"' | '`' | '[' | null = null;

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index]!;
    const next = input[index + 1];

    if (quote) {
      current += char;

      if (quote === "'" && char === "'" && next === "'") {
        current += next;
        index += 1;
        continue;
      }

      if (quote === '"' && char === '"' && next === '"') {
        current += next;
        index += 1;
        continue;
      }

      if (quote === '`' && char === '`' && next === '`') {
        current += next;
        index += 1;
        continue;
      }

      if (quote === '[' && char === ']' && next === ']') {
        current += next;
        index += 1;
        continue;
      }

      if ((quote === '[' && char === ']') || (quote !== '[' && char === quote)) {
        quote = null;
      }
      continue;
    }

    if (char === "'" || char === '"' || char === '`' || char === '[') {
      quote = char;
      current += char;
      continue;
    }

    if (char === '(') {
      depth += 1;
      current += char;
      continue;
    }

    if (char === ')') {
      depth = Math.max(0, depth - 1);
      current += char;
      continue;
    }

    if (char === separator && depth === 0) {
      const fragment = current.trim();

      if (fragment) {
        fragments.push(fragment);
      }
      current = '';
      continue;
    }

    current += char;
  }

  const tail = current.trim();

  if (tail) {
    fragments.push(tail);
  }

  return fragments;
}

function findTopLevelCharacter(input: string, target: string): number {
  let depth = 0;
  let quote: "'" | '"' | '`' | '[' | null = null;

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index]!;
    const next = input[index + 1];

    if (quote) {
      if (
        (quote === "'" && char === "'" && next === "'") ||
        (quote === '"' && char === '"' && next === '"') ||
        (quote === '`' && char === '`' && next === '`') ||
        (quote === '[' && char === ']' && next === ']')
      ) {
        index += 1;
        continue;
      }

      if ((quote === '[' && char === ']') || (quote !== '[' && char === quote)) {
        quote = null;
      }
      continue;
    }

    if (char === "'" || char === '"' || char === '`' || char === '[') {
      quote = char;
      continue;
    }

    if (char === target && depth === 0) {
      return index;
    }

    if (char === '(') {
      depth += 1;
      continue;
    }

    if (char === ')') {
      depth = Math.max(0, depth - 1);
    }
  }

  return -1;
}

function findMatchingParenthesis(input: string, startIndex: number): number {
  let depth = 0;
  let quote: "'" | '"' | '`' | '[' | null = null;

  for (let index = startIndex; index < input.length; index += 1) {
    const char = input[index]!;
    const next = input[index + 1];

    if (quote) {
      if (
        (quote === "'" && char === "'" && next === "'") ||
        (quote === '"' && char === '"' && next === '"') ||
        (quote === '`' && char === '`' && next === '`') ||
        (quote === '[' && char === ']' && next === ']')
      ) {
        index += 1;
        continue;
      }

      if ((quote === '[' && char === ']') || (quote !== '[' && char === quote)) {
        quote = null;
      }
      continue;
    }

    if (char === "'" || char === '"' || char === '`' || char === '[') {
      quote = char;
      continue;
    }

    if (char === '(') {
      depth += 1;
      continue;
    }

    if (char === ')') {
      depth -= 1;

      if (depth === 0) {
        return index;
      }
    }
  }

  return -1;
}

function readParenthesizedContent(input: string, startIndex: number): string | null {
  if (startIndex < 0 || input[startIndex] !== '(') {
    return null;
  }

  const endIndex = findMatchingParenthesis(input, startIndex);

  return endIndex > startIndex ? input.slice(startIndex + 1, endIndex).trim() : null;
}

function readLeadingIdentifier(fragment: string): { rest: string; value: string } | null {
  const trimmed = fragment.trim();

  if (!trimmed) {
    return null;
  }

  if (trimmed.startsWith('"') || trimmed.startsWith('`') || trimmed.startsWith('[')) {
    const quote = trimmed[0] as '"' | '`' | '[';
    const endQuote = quote === '[' ? ']' : quote;
    let raw = '';

    for (let index = 1; index < trimmed.length; index += 1) {
      const char = trimmed[index]!;
      const next = trimmed[index + 1];

      if (char === endQuote && next === endQuote) {
        raw += endQuote;
        index += 1;
        continue;
      }

      if (char === endQuote) {
        return {
          rest: trimmed.slice(index + 1).trim(),
          value: raw,
        };
      }

      raw += char;
    }

    return null;
  }

  const match = trimmed.match(/^([^\s(),]+)([\s\S]*)$/);

  return match
    ? {
        rest: (match[2] ?? '').trim(),
        value: stripIdentifierQuotes(match[1] ?? ''),
      }
    : null;
}

function splitColumnTypeAndConstraints(input: string): { constraints: string; typeRaw: string } {
  const constraintStarters = new Set([
    'AUTO_INCREMENT',
    'CHECK',
    'COLLATE',
    'COMMENT',
    'CONSTRAINT',
    'DEFAULT',
    'GENERATED',
    'IDENTITY',
    'NOT',
    'NULL',
    'PRIMARY',
    'REFERENCES',
    'UNIQUE',
  ]);
  let depth = 0;
  let quote: "'" | '"' | '`' | '[' | null = null;

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index]!;
    const next = input[index + 1];

    if (quote) {
      if (
        (quote === "'" && char === "'" && next === "'") ||
        (quote === '"' && char === '"' && next === '"') ||
        (quote === '`' && char === '`' && next === '`') ||
        (quote === '[' && char === ']' && next === ']')
      ) {
        index += 1;
        continue;
      }

      if ((quote === '[' && char === ']') || (quote !== '[' && char === quote)) {
        quote = null;
      }
      continue;
    }

    if (char === "'" || char === '"' || char === '`' || char === '[') {
      quote = char;
      continue;
    }

    if (char === '(') {
      depth += 1;
      continue;
    }

    if (char === ')') {
      depth = Math.max(0, depth - 1);
      continue;
    }

    if (depth === 0 && (index === 0 || /\s/.test(input[index - 1] ?? '')) && /[A-Za-z_]/.test(char)) {
      const word = input.slice(index).match(/^[A-Za-z_][A-Za-z0-9_]*/)?.[0] ?? '';

      if (constraintStarters.has(word.toUpperCase())) {
        return {
          constraints: input.slice(index).trim(),
          typeRaw: input.slice(0, index).trim(),
        };
      }
    }
  }

  return {
    constraints: '',
    typeRaw: input.trim(),
  };
}

function parseInlineEnumValues(typeRaw: string): string[] | undefined {
  const match = typeRaw.trim().match(/^ENUM\s*\(([\s\S]*)\)$/i);

  return match ? parseSqlStringList(match[1] ?? '') : undefined;
}

function parseSqlStringList(input: string): string[] {
  return splitTopLevel(input, ',').map((value) => {
    const trimmed = value.trim();

    if (trimmed.startsWith("'") && trimmed.endsWith("'")) {
      return trimmed.slice(1, -1).replaceAll("''", "'");
    }

    return normalizeIdentifier(trimmed);
  });
}

function extractDefaultValue(constraints: string): string | undefined {
  const defaultIndex = findTopLevelWord(constraints, 'DEFAULT');

  if (defaultIndex < 0) {
    return undefined;
  }

  const afterDefault = constraints.slice(defaultIndex + 'DEFAULT'.length).trimStart();
  const nextConstraintIndex = findNextTopLevelConstraintWord(afterDefault);
  const value = (nextConstraintIndex >= 0 ? afterDefault.slice(0, nextConstraintIndex) : afterDefault).trim();

  return value || undefined;
}

function isTableConstraintFragment(fragment: string): boolean {
  const { body } = stripConstraintName(fragment);

  return /^(?:PRIMARY\s+KEY|UNIQUE|FOREIGN\s+KEY|CHECK|KEY|INDEX)\b/i.test(body);
}

function stripConstraintName(fragment: string): { body: string; name?: string } {
  const body = fragment.trim();

  if (!/^CONSTRAINT\b/i.test(body)) {
    return { body };
  }

  const afterConstraint = body.replace(/^CONSTRAINT\b/i, '').trim();
  const identifier = readLeadingIdentifier(afterConstraint);

  if (!identifier) {
    return { body: afterConstraint };
  }

  return {
    body: identifier.rest,
    name: identifier.value,
  };
}

function parseFirstColumnList(input: string): string[] {
  const startIndex = findTopLevelCharacter(input, '(');
  const content = readParenthesizedContent(input, startIndex);

  return content ? parseColumnList(content) : [];
}

function parseColumnList(input: string): string[] {
  return splitTopLevel(input, ',').flatMap((fragment) => {
    const cleaned = fragment
      .replace(/\b(?:ASC|DESC)\b/gi, '')
      .replace(/\bNULLS\s+(?:FIRST|LAST)\b/gi, '')
      .trim();
    const identifier = readLeadingIdentifier(cleaned);

    return identifier ? [identifier.value] : [];
  });
}

function parseReferentialAction(
  fragment: string,
  event: 'DELETE' | 'UPDATE',
): DatabaseRelationship['onDelete'] | undefined {
  const match = fragment.match(
    new RegExp(`\\bON\\s+${event}\\s+(CASCADE|RESTRICT|SET\\s+NULL|SET\\s+DEFAULT|NO\\s+ACTION)\\b`, 'i'),
  );
  const action = match?.[1]?.replace(/\s+/g, ' ').toUpperCase();

  if (action === 'CASCADE') {
    return 'cascade';
  }

  if (action === 'RESTRICT') {
    return 'restrict';
  }

  if (action === 'SET NULL') {
    return 'set_null';
  }

  if (action === 'SET DEFAULT') {
    return 'set_default';
  }

  if (action === 'NO ACTION') {
    return 'no_action';
  }

  return undefined;
}

function rememberEnum(context: SqlImportContext, name: SqlQualifiedName, enumId: string) {
  context.enumIdsByName.set(qualifiedNameKey(name), enumId);
  context.enumIdsByName.set(name.name.toLowerCase(), enumId);
}

function rememberTable(context: SqlImportContext, name: SqlQualifiedName, tableId: string) {
  context.tableIdsByName.set(qualifiedNameKey(name), tableId);
  context.tableIdsByName.set(name.name.toLowerCase(), tableId);
}

function qualifiedNameKey(name: SqlQualifiedName): string {
  return name.schema ? `${name.schema.toLowerCase()}.${name.name.toLowerCase()}` : name.name.toLowerCase();
}

function formatQualifiedName(name: SqlQualifiedName): string {
  return name.schema ? `${name.schema}.${name.name}` : name.name;
}

function createUniqueId(context: SqlImportContext, prefix: string, seed: string): string {
  const baseId = `${prefix}-${slugifyIdentifier(seed)}`;
  let candidate = baseId;
  let counter = 2;

  while (context.usedIds.has(candidate)) {
    candidate = `${baseId}-${counter}`;
    counter += 1;
  }

  context.usedIds.add(candidate);

  return candidate;
}

function slugifyIdentifier(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'item'
  );
}

function parseQualifiedName(input: string): SqlQualifiedName {
  const parts = splitIdentifierPath(input).map(normalizeIdentifier).filter(Boolean);
  const name = parts.at(-1) ?? normalizeIdentifier(input);
  const schema = parts.length > 1 ? parts.at(-2) : undefined;

  return schema ? { name, schema } : { name };
}

function splitIdentifierPath(input: string): string[] {
  return splitTopLevelByDot(input.trim()).filter(Boolean);
}

function splitTopLevelByDot(input: string): string[] {
  const parts: string[] = [];
  let current = '';
  let quote: '"' | '`' | '[' | null = null;

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index]!;
    const next = input[index + 1];

    if (quote) {
      current += char;

      if (
        (quote === '"' && char === '"' && next === '"') ||
        (quote === '`' && char === '`' && next === '`') ||
        (quote === '[' && char === ']' && next === ']')
      ) {
        current += next;
        index += 1;
        continue;
      }

      if ((quote === '[' && char === ']') || (quote !== '[' && char === quote)) {
        quote = null;
      }
      continue;
    }

    if (char === '"' || char === '`' || char === '[') {
      quote = char;
      current += char;
      continue;
    }

    if (char === '.') {
      parts.push(current.trim());
      current = '';
      continue;
    }

    current += char;
  }

  if (current.trim()) {
    parts.push(current.trim());
  }

  return parts;
}

function normalizeIdentifier(input: string): string {
  const trimmed = input.trim();

  if (trimmed.includes('.')) {
    return parseQualifiedName(trimmed).name;
  }

  return stripIdentifierQuotes(trimmed);
}

function stripIdentifierQuotes(input: string): string {
  const trimmed = input.trim().replace(/,$/, '');

  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    return trimmed.slice(1, -1).replaceAll('""', '"');
  }

  if (trimmed.startsWith('`') && trimmed.endsWith('`')) {
    return trimmed.slice(1, -1).replaceAll('``', '`');
  }

  if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
    return trimmed.slice(1, -1).replaceAll(']]', ']');
  }

  return trimmed;
}

function findColumnIdByName(context: SqlImportContext, tableId: string, columnName: string): string | undefined {
  const table = context.model.tables[tableId];
  const normalizedColumnName = normalizeIdentifier(columnName).toLowerCase();

  return table?.columnIds.find(
    (columnId) => context.model.columns[columnId]?.name.toLowerCase() === normalizedColumnName,
  );
}

function resolveTableId(context: SqlImportContext, name: SqlQualifiedName): string | undefined {
  return context.tableIdsByName.get(qualifiedNameKey(name)) ?? context.tableIdsByName.get(name.name.toLowerCase());
}

function findTopLevelWord(input: string, word: string): number {
  let depth = 0;
  let quote: "'" | '"' | '`' | '[' | null = null;

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index]!;
    const next = input[index + 1];

    if (quote) {
      if (
        (quote === "'" && char === "'" && next === "'") ||
        (quote === '"' && char === '"' && next === '"') ||
        (quote === '`' && char === '`' && next === '`') ||
        (quote === '[' && char === ']' && next === ']')
      ) {
        index += 1;
        continue;
      }

      if ((quote === '[' && char === ']') || (quote !== '[' && char === quote)) {
        quote = null;
      }
      continue;
    }

    if (char === "'" || char === '"' || char === '`' || char === '[') {
      quote = char;
      continue;
    }

    if (char === '(') {
      depth += 1;
      continue;
    }

    if (char === ')') {
      depth = Math.max(0, depth - 1);
      continue;
    }

    if (
      depth === 0 &&
      input.slice(index, index + word.length).toUpperCase() === word &&
      !/[A-Za-z0-9_]/.test(input[index - 1] ?? '') &&
      !/[A-Za-z0-9_]/.test(input[index + word.length] ?? '')
    ) {
      return index;
    }
  }

  return -1;
}

function findNextTopLevelConstraintWord(input: string): number {
  const words = ['CONSTRAINT', 'PRIMARY', 'NOT', 'NULL', 'UNIQUE', 'REFERENCES', 'CHECK', 'COLLATE', 'COMMENT'];
  const indexes = words.map((word) => findTopLevelWord(input, word)).filter((index) => index > 0);

  return indexes.length > 0 ? Math.min(...indexes) : -1;
}

function renderCreateTableStatement(model: DiagramModel, table: DatabaseTable, options: GenerateSqlOptions): string {
  const dialect = options.dialect;
  const includeComments = options.includeComments ?? true;
  const columns = getTableColumns(model, table.id);
  const primaryKeyColumns = columns.filter((column) => column.primaryKey);
  const checks = Object.values(model.checks).filter((check) => check.tableId === table.id);
  const relationships = Object.values(model.relationships).filter(
    (relationship) => relationship.targetTableId === table.id,
  );
  const bodyLines = [
    ...columns.map((column) =>
      renderColumn(column, model, dialect, {
        includeComments,
        renderInlinePrimaryKey: primaryKeyColumns.length === 1,
        renderInlineUnique: shouldRenderInlineUnique(model, column),
      }),
    ),
    primaryKeyColumns.length > 1 ? renderCompositePrimaryKey(primaryKeyColumns, table, dialect) : null,
    ...checks.flatMap((check) =>
      sqlDialectRegistry[dialect].supportsCheckConstraints ? [renderCheckConstraint(check, dialect)] : [],
    ),
    ...relationships.flatMap((relationship) => renderForeignKeyConstraint(model, relationship, dialect)),
  ].filter((line): line is string => Boolean(line));
  const body = bodyLines.length > 0 ? bodyLines.map((line) => `  ${line}`).join(',\n') : '  -- No columns defined yet';
  const tableComment =
    includeComments && sqlDialectRegistry[dialect].supportsTableCommentOption && table.comment
      ? ` COMMENT=${quoteStringLiteral(table.comment)}`
      : '';

  return `CREATE TABLE ${renderTableName(table, dialect)} (\n${body}\n)${tableComment};`;
}

function renderColumn(
  column: DatabaseColumn,
  model: DiagramModel,
  dialect: SqlDialect,
  options: {
    includeComments: boolean;
    renderInlinePrimaryKey: boolean;
    renderInlineUnique: boolean;
  },
): string {
  const definition: DialectDefinition = sqlDialectRegistry[dialect];
  const parts = [
    quoteIdentifier(column.name, dialect),
    renderType(column.type, model, dialect),
    column.unsigned && definition.supportsUnsigned ? 'UNSIGNED' : undefined,
    column.autoIncrement && definition.autoIncrementKeyword ? definition.autoIncrementKeyword : undefined,
    column.primaryKey && options.renderInlinePrimaryKey ? 'PRIMARY KEY' : undefined,
    column.nullable ? undefined : 'NOT NULL',
    column.unique && options.renderInlineUnique ? 'UNIQUE' : undefined,
    column.defaultValue ? `DEFAULT ${column.defaultValue}` : undefined,
    options.includeComments && column.comment && definition.supportsColumnComments
      ? `COMMENT ${quoteStringLiteral(column.comment)}`
      : undefined,
  ];

  // Undefined fragments are filtered so each dialect can opt into only the constraints it understands.
  return parts.filter(Boolean).join(' ');
}

function shouldRenderInlineUnique(model: DiagramModel, column: DatabaseColumn): boolean {
  const hasNamedSingleColumnUniqueIndex = Object.values(model.indexes).some(
    (index) =>
      index.tableId === column.tableId &&
      index.unique &&
      index.columns.length === 1 &&
      index.columns[0]?.columnId === column.id,
  );

  // If the user has a named unique index for this column, the index statement owns the SQL instead of duplicating UNIQUE inline.
  return !hasNamedSingleColumnUniqueIndex;
}

function renderCompositePrimaryKey(columns: DatabaseColumn[], table: DatabaseTable, dialect: SqlDialect): string {
  const constraintName = `${table.name}_pkey`;
  const columnNames = columns.map((column) => quoteIdentifier(column.name, dialect)).join(', ');

  return `CONSTRAINT ${quoteIdentifier(constraintName, dialect)} PRIMARY KEY (${columnNames})`;
}

function renderCheckConstraint(check: DatabaseCheck, dialect: SqlDialect): string {
  // Checks are table constraints so a later expression can reference multiple columns without changing the model shape.
  return `CONSTRAINT ${quoteIdentifier(check.name, dialect)} CHECK (${check.expression})`;
}

function renderForeignKeyConstraint(
  model: DiagramModel,
  relationship: DatabaseRelationship,
  dialect: SqlDialect,
): string[] {
  const sourceTable = model.tables[relationship.sourceTableId];
  const targetTable = model.tables[relationship.targetTableId];

  if (!sourceTable || !targetTable) {
    return [];
  }

  const sourceColumns = relationship.sourceColumnIds.flatMap((columnId) => {
    const column = model.columns[columnId];
    return column ? [quoteIdentifier(column.name, dialect)] : [];
  });
  const targetColumns = relationship.targetColumnIds.flatMap((columnId) => {
    const column = model.columns[columnId];
    return column ? [quoteIdentifier(column.name, dialect)] : [];
  });
  const targetColumnNames = relationship.targetColumnIds.flatMap((columnId) => {
    const column = model.columns[columnId];
    return column ? [column.name] : [];
  });

  if (sourceColumns.length === 0 || targetColumns.length === 0 || sourceColumns.length !== targetColumns.length) {
    return [];
  }

  const parts = [
    // The fallback constraint name uses raw column names first, then the final identifier quoting handles the active dialect.
    `CONSTRAINT ${quoteIdentifier(relationship.name ?? `${targetTable.name}_${targetColumnNames.join('_')}_fkey`, dialect)}`,
    `FOREIGN KEY (${targetColumns.join(', ')})`,
    `REFERENCES ${renderTableName(sourceTable, dialect)} (${sourceColumns.join(', ')})`,
    relationship.matchType && relationship.matchType !== 'simple' && dialect === 'postgresql'
      ? `MATCH ${relationship.matchType.toUpperCase()}`
      : undefined,
    relationship.onDelete ? `ON DELETE ${renderReferentialAction(relationship.onDelete)}` : undefined,
    relationship.onUpdate ? `ON UPDATE ${renderReferentialAction(relationship.onUpdate)}` : undefined,
    relationship.deferrable && sqlDialectRegistry[dialect].supportsDeferrableConstraints ? 'DEFERRABLE' : undefined,
  ];

  return [parts.filter(Boolean).join(' ')];
}

function renderIndexStatements(model: DiagramModel, dialect: SqlDialect): string[] {
  return Object.values(model.indexes).flatMap((index) => {
    const table = model.tables[index.tableId];

    if (!table || index.columns.length === 0) {
      return [];
    }

    const renderedColumns = index.columns.flatMap((indexColumn) => {
      const column = model.columns[indexColumn.columnId];

      if (!column) {
        return [];
      }

      const direction = indexColumn.order ? ` ${indexColumn.order.toUpperCase()}` : '';
      const nulls = indexColumn.nulls && dialect === 'postgresql' ? ` NULLS ${indexColumn.nulls.toUpperCase()}` : '';

      return [`${quoteIdentifier(column.name, dialect)}${direction}${nulls}`];
    });

    if (renderedColumns.length === 0) {
      return [];
    }

    const definition: DialectDefinition = sqlDialectRegistry[dialect];
    const unique = index.unique ? 'UNIQUE ' : '';
    const method = renderIndexMethod(index, dialect);
    const include =
      index.includeColumnIds?.length && definition.supportsIndexInclude
        ? ` INCLUDE (${renderIndexIncludeColumns(model, index, dialect).join(', ')})`
        : '';
    const where = index.where && definition.supportsFilteredIndexes ? ` WHERE ${index.where}` : '';

    return [
      `CREATE ${unique}INDEX ${quoteIdentifier(index.name, dialect)}${method} ON ${renderTableName(table, dialect)} (${renderedColumns.join(', ')})${include}${where};`,
    ];
  });
}

function renderIndexMethod(index: DatabaseIndex, dialect: SqlDialect): string {
  if (!index.method || !sqlDialectRegistry[dialect].supportsIndexMethods) {
    return '';
  }

  if (dialect === 'postgresql') {
    return ` USING ${index.method}`;
  }

  if ((dialect === 'mysql' || dialect === 'mariadb') && (index.method === 'btree' || index.method === 'hash')) {
    return ` USING ${index.method.toUpperCase()}`;
  }

  return '';
}

function renderIndexIncludeColumns(model: DiagramModel, index: DatabaseIndex, dialect: SqlDialect): string[] {
  return (index.includeColumnIds ?? []).flatMap((columnId) => {
    const column = model.columns[columnId];
    return column ? [quoteIdentifier(column.name, dialect)] : [];
  });
}

function renderType(type: ColumnTypeSpec, model: DiagramModel, dialect: SqlDialect): string {
  if (type.raw) {
    return type.raw;
  }

  if (type.family === 'enum') {
    return renderEnumType(type, model, dialect);
  }

  const typeRenderer = typeRenderers[dialect][type.family];

  return typeRenderer(type);
}

const typeRenderers = {
  mariadb: {
    bigint: () => 'BIGINT',
    boolean: () => 'BOOLEAN',
    date: () => 'DATE',
    decimal: (type) => `DECIMAL(${type.precision ?? 10}, ${type.scale ?? 2})`,
    float: () => 'DOUBLE',
    integer: () => 'INT',
    json: () => 'JSON',
    text: () => 'TEXT',
    time: () => 'TIME',
    timestamp: () => 'DATETIME',
    uuid: () => 'CHAR(36)',
    varchar: (type) => `VARCHAR(${type.length ?? 255})`,
  },
  mysql: {
    bigint: () => 'BIGINT',
    boolean: () => 'BOOLEAN',
    date: () => 'DATE',
    decimal: (type) => `DECIMAL(${type.precision ?? 10}, ${type.scale ?? 2})`,
    float: () => 'DOUBLE',
    integer: () => 'INT',
    json: () => 'JSON',
    text: () => 'TEXT',
    time: () => 'TIME',
    timestamp: () => 'DATETIME',
    uuid: () => 'CHAR(36)',
    varchar: (type) => `VARCHAR(${type.length ?? 255})`,
  },
  postgresql: {
    bigint: () => 'BIGINT',
    boolean: () => 'BOOLEAN',
    date: () => 'DATE',
    decimal: (type) => `NUMERIC(${type.precision ?? 10}, ${type.scale ?? 2})`,
    float: () => 'DOUBLE PRECISION',
    integer: () => 'INTEGER',
    json: () => 'JSONB',
    text: () => 'TEXT',
    time: () => 'TIME',
    timestamp: () => 'TIMESTAMPTZ',
    uuid: () => 'UUID',
    varchar: (type) => `VARCHAR(${type.length ?? 255})`,
  },
  sqlite: {
    bigint: () => 'INTEGER',
    boolean: () => 'INTEGER',
    date: () => 'TEXT',
    decimal: () => 'NUMERIC',
    float: () => 'REAL',
    integer: () => 'INTEGER',
    json: () => 'TEXT',
    text: () => 'TEXT',
    time: () => 'TEXT',
    timestamp: () => 'TEXT',
    uuid: () => 'TEXT',
    varchar: (type) => `VARCHAR(${type.length ?? 255})`,
  },
  sqlserver: {
    bigint: () => 'BIGINT',
    boolean: () => 'BIT',
    date: () => 'DATE',
    decimal: (type) => `DECIMAL(${type.precision ?? 10}, ${type.scale ?? 2})`,
    float: () => 'FLOAT',
    integer: () => 'INT',
    json: () => 'NVARCHAR(MAX)',
    text: () => 'NVARCHAR(MAX)',
    time: () => 'TIME',
    timestamp: () => 'DATETIME2',
    uuid: () => 'UNIQUEIDENTIFIER',
    varchar: (type) => `NVARCHAR(${type.length ?? 255})`,
  },
} satisfies Record<SqlDialect, Record<Exclude<ColumnTypeSpec['family'], 'enum'>, (type: ColumnTypeSpec) => string>>;

function renderEnumStatements(model: DiagramModel, dialect: SqlDialect): string[] {
  if (dialect !== 'postgresql') {
    return [];
  }

  return Object.values(model.enums).map((databaseEnum) => {
    const enumName = renderQualifiedName(databaseEnum.schema, databaseEnum.name, dialect);
    const values = databaseEnum.values.map(quoteStringLiteral).join(', ');

    // PostgreSQL enum types must be declared before tables can reference them.
    return `CREATE TYPE ${enumName} AS ENUM (${values});`;
  });
}

function renderEnumType(type: ColumnTypeSpec, model: DiagramModel, dialect: SqlDialect): string {
  const databaseEnum = type.enumId ? model.enums[type.enumId] : undefined;

  if (!databaseEnum) {
    return renderTextFallbackType(dialect);
  }

  if (dialect === 'postgresql') {
    return renderQualifiedName(databaseEnum.schema, databaseEnum.name, dialect);
  }

  if (sqlDialectRegistry[dialect].supportsInlineEnum) {
    return `ENUM(${databaseEnum.values.map(quoteStringLiteral).join(', ')})`;
  }

  return renderTextFallbackType(dialect);
}

function renderTextFallbackType(dialect: SqlDialect): string {
  return dialect === 'sqlserver' ? 'NVARCHAR(MAX)' : 'TEXT';
}

function renderCommentStatements(model: DiagramModel, dialect: SqlDialect): string[] {
  if (!sqlDialectRegistry[dialect].supportsSeparateCommentStatements) {
    return [];
  }

  return [
    ...Object.values(model.enums).flatMap((databaseEnum) =>
      databaseEnum.comment
        ? [
            `COMMENT ON TYPE ${renderQualifiedName(databaseEnum.schema, databaseEnum.name, dialect)} IS ${quoteStringLiteral(databaseEnum.comment)};`,
          ]
        : [],
    ),
    ...Object.values(model.tables).flatMap((table) => {
      const tableName = renderTableName(table, dialect);
      const columns = getTableColumns(model, table.id);
      const checks = Object.values(model.checks).filter((check) => check.tableId === table.id);
      const indexes = Object.values(model.indexes).filter((index) => index.tableId === table.id);

      return [
        table.comment ? `COMMENT ON TABLE ${tableName} IS ${quoteStringLiteral(table.comment)};` : null,
        ...columns.map((column) =>
          column.comment
            ? `COMMENT ON COLUMN ${tableName}.${quoteIdentifier(column.name, dialect)} IS ${quoteStringLiteral(column.comment)};`
            : null,
        ),
        ...checks.map((check) =>
          check.comment
            ? `COMMENT ON CONSTRAINT ${quoteIdentifier(check.name, dialect)} ON ${tableName} IS ${quoteStringLiteral(check.comment)};`
            : null,
        ),
        ...indexes.map((index) =>
          index.comment
            ? `COMMENT ON INDEX ${quoteIdentifier(index.name, dialect)} IS ${quoteStringLiteral(index.comment)};`
            : null,
        ),
      ].filter((statement): statement is string => Boolean(statement));
    }),
  ];
}

function renderTableName(table: DatabaseTable, dialect: SqlDialect): string {
  return renderQualifiedName(table.schema, table.name, dialect);
}

function renderQualifiedName(schema: string | undefined, name: string, dialect: SqlDialect): string {
  if (!schema || !sqlDialectRegistry[dialect].supportsSchemas) {
    return quoteIdentifier(name, dialect);
  }

  return `${quoteIdentifier(schema, dialect)}.${quoteIdentifier(name, dialect)}`;
}

function quoteIdentifier(value: string, dialect: SqlDialect): string {
  const quote = sqlDialectRegistry[dialect].identifierQuote;

  if (quote === 'backtick') {
    return `\`${value.replaceAll('`', '``')}\``;
  }

  if (quote === 'bracket') {
    return `[${value.replaceAll(']', ']]')}]`;
  }

  return `"${value.replaceAll('"', '""')}"`;
}

function quoteStringLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function renderReferentialAction(action: NonNullable<DatabaseRelationship['onDelete']>): string {
  return action.replaceAll('_', ' ').toUpperCase();
}
